"""add_vacation_tracking_to_user_settings

Revision ID: 3c6492af3a32
Revises: 42b9a05781dd
Create Date: 2026-01-30 12:06:17.349558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6492af3a32'
down_revision: Union[str, Sequence[str], None] = '42b9a05781dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_vacation_days', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('annual_vacation_days', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('vacation_carryover_days', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('vacation_carryover_expires', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('vacation_carryover_expires')
        batch_op.drop_column('vacation_carryover_days')
        batch_op.drop_column('annual_vacation_days')
        batch_op.drop_column('initial_vacation_days')

    # ### end Alembic commands ###
