"""remove carryover_hours from user_settings

Revision ID: 42b9a05781dd
Revises: e385869d5a44
Create Date: 2026-01-30 10:19:17.319537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b9a05781dd'
down_revision: Union[str, Sequence[str], None] = 'e385869d5a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('carryover_hours')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carryover_hours', sa.NUMERIC(precision=6, scale=2), nullable=True))

    # ### end Alembic commands ###
