"""add_tracking_settings_to_user_settings

Revision ID: e385869d5a44
Revises: b5be5923b848
Create Date: 2026-01-28 19:47:29.280676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e385869d5a44'
down_revision: Union[str, Sequence[str], None] = 'b5be5923b848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('initial_hours_offset', sa.Numeric(precision=6, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('initial_hours_offset')
        batch_op.drop_column('tracking_start_date')

    # ### end Alembic commands ###
